apiVersion: v1
kind: PersistentVolume
metadata:
  name: timelapse-nas-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 192.168.0.39
    path: /volume1/auto-timelapse
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: timelapse-output-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.39
    path: /volume1/auto-timelapse
  persistentVolumeReclaimPolicy: Retain
