apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timelapse-nas-pvc
  namespace: default
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
  volumeName: timelapse-nas-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timelapse-output-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: timelapse-output-pv
  storageClassName: ""
